name: Configure internal registry
description: Configure internal registry

inputs:
  registry-password:
    description: Internal registry password
    required: true

  registry-uri:
    description: Internal registry uri
    required: true

runs:
  using: composite
  steps:
    - name: Creating root ~/.npmrc file with internal registry config
      run: |
        touch ~/.npmrc
        echo "@stardustsoft:registry=https:${{ inputs.registry-uri }}/" >> ~/.npmrc
        echo "${{ inputs.registry-uri }}/:username=santiago-stardust" >> ~/.npmrc
        echo "${{ inputs.registry-uri }}/:email=github@santiago-stardust.aleeas.com" >> ~/.npmrc
        echo "${{ inputs.registry-uri }}/:_authToken=${{ inputs.registry-password }}" >> ~/.npmrc
      shell: bash
