name: Configure internal registry
description: Configure internal registry

inputs:
  registry-password:
    description: Internal registry password
    required: true

  registry-uri:
    description: Internal registry uri
    required: true

runs:
  using: composite
  steps:
    - name: Creating root ~/.npmrc file with internal registry config
      run: |
        touch ~/.npmrc
        echo "STARDUST_REGISTRY_TOKEN=${{ inputs.registry-password }}" >> $GITHUB_ENV
        echo "@stardustsoft:registry=https://npm.pkg.github.com/" >> ~/.npmrc
        echo "//npm.pkg.github.com/:_authToken=${{ inputs.registry-password }}" >> ~/.npmrc
      shell: bash
