name: Configure internal registry
description: Configure internal registry

inputs:
  registry-access-token:
    description: Internal registry access token
    required: true

runs:
  using: composite
  steps:
    - name: Creating root ~/.npmrc file with internal registry config
      run: |
        touch ~/.npmrc
        echo "STARDUST_REGISTRY_TOKEN=${{ inputs.registry-access-token }}" >> $GITHUB_ENV
        echo "@stardustsoft:registry=https://npm.pkg.github.com/" >> ~/.npmrc
        echo "//npm.pkg.github.com/:_authToken=${{ inputs.registry-access-token }}" >> ~/.npmrc
      shell: bash
