name: Checkout and run yarn install
description: Checkouts out commit, sets up Node, and installs dependencies.

inputs:
  install-cache-name:
    description: Install cache name
    required: true

  registry-access-token:
    description: Internal registry access token
    required: true

runs:
  using: composite
  steps:
    - name: Checkout the commit
      uses: actions/checkout@v2

    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Configure internal registry
      uses: stardusttech-io/gha/.github/actions/configure-registry@master
      with:
        registry-access-token: ${{ inputs.registry-access-token }}

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ./node_modules
        key: ${{ runner.os }}-${{ inputs.install-cache-name }}-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.install-cache-name }}-
          ${{ runner.os }}-

    - run: |
        if [[ "${{ steps.cache-dependencies.outputs.cache-hit }}" != "true" ]]; then yarn; fi
      shell: bash
