name: Publish internal package
description: Publish internal package

inputs:
  id:
    description: Identifier used for cache and artifacts
    required: true

  persist:
    description: Paths to persist
    required: true

  registry-password:
    description: Internal registry password
    required: true

  registry-uri:
    description: Internal registry uri
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - uses: actions/download-artifact@v2
      if: ${{ inputs.persist }}
      with:
        name: ${{ inputs.id }}

    - uses: stardusttech-io/gha/.github/actions/configure-registry@master
      with:
        registry-password: ${{ inputs.registry-password }}
        registry-uri: ${{ inputs.registry-uri }}

    - uses: stardusttech-io/gha/.github/actions/configure-git@master

    - run: npm version patch --message "v%s [skip ci]"
      shell: bash

    - run: git push
      shell: bash

    - run: npm publish
      shell: bash
