name: Publish internal package
description: Publish internal package

inputs:
  build-artifact-name:
    description: Build artifact name
    required: false

  persist:
    description: Paths to persist
    required: false

  registry-access-token:
    description: Internal registry access token
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - run: git pull
      shell: bash

    - uses: actions/download-artifact@v2
      if: ${{ inputs.persist }}
      with:
        name: ${{ inputs.build-artifact-name }}

    - uses: stardusttech-io/gha/.github/actions/configure-registry@master
      with:
        registry-access-token: ${{ inputs.registry-access-token }}

    - uses: stardusttech-io/gha/.github/actions/configure-git@master

    - run: npm version patch --message "v%s [skip ci]"
      shell: bash

    - run: git push
      shell: bash

    - run: npm publish
      shell: bash
