name: Authenticate Internal Registry

description: Authenticate internal registry.

inputs:
  registry-uri:
    description: Registry URI
    required: true

  registry-password:
    description: Registry password
    required: true

runs:
  using: composite
  steps:
    - name: Creating global .npmrc file
      run: touch ~/.npmrc
      shell: bash
    - name: Appending registry password
      run: echo "${{ inputs.registry-uri }}/:_password=${{ inputs.registry-password }}" >>~/.npmrc
      shell: bash
    - name: Appending registry username
      run: echo "${{ inputs.registry-uri }}/:username=_json_key_base64" >>~/.npmrc
      shell: bash
    - name: Appending registry email
      run: echo "${{ inputs.registry-uri }}/:email=not.valid@email.com" >>~/.npmrc
      shell: bash
    - name: Echoing output
      run: cat ~/.npmrc
      shell: bash
