name: Authenticate Internal Registry

description: Authenticate internal registry.

inputs:
  registry-password:
    description: Registry password
    required: true

runs:
  using: composite
  steps:
    - name: Creating global .npmrc file
      run: touch ~/.npmrc
      shell: bash

    - name: Appending scoped @stardust registry
      run: echo "@stardust:registry=https://us-east1-npm.pkg.dev/stardusttech-io/stardust-registry/" >> ~/.npmrc
      shell: bash

    - name: Appending registry password
      run: echo "//us-east1-npm.pkg.dev/stardusttech-io/stardust-registry/:_password=${{ inputs.registry-password }}" >> ~/.npmrc
      shell: bash

    - name: Appending registry username
      run: echo "//us-east1-npm.pkg.dev/stardusttech-io/stardust-registry/:username=_json_key_base64" >> ~/.npmrc
      shell: bash

    - name: Appending registry email
      run: echo "//us-east1-npm.pkg.dev/stardusttech-io/stardust-registry/:email=not.valid@email.com" >> ~/.npmrc
      shell: bash

    - name: Echoing output
      run: cat ~/.npmrc
      shell: bash
