name: Install dependencies
description: Install dependencies

inputs:
  registry-password:
    description: Internal registry password
    required: true

  registry-uri:
    description: Internal registry uri
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - uses: stardusttech-io/actions/.github/actions/configure-registry@master
      with:
        password: ${{ inputs.registry-password }}
        uri: ${{ inputs.registry-uri }}

    - uses: stardusttech-io/actions/.github/actions/npm-cache@master

    - run: npm run install
      shell: bash
