name: Lint
description: Lint

inputs:
  id:
    description: Identifier used for cache and artifacts
    required: true

  registry-password:
    description: Internal registry password
    required: true

  registry-uri:
    description: Internal registry uri
    required: true

runs:
  using: composite
  steps:
    - uses: stardusttech-io/gha/.github/actions/checkout-and-install@master
      with:
        id: ${{ inputs.id }}
        registry-password: ${{ inputs.registry-password }}
        registry-uri: ${{ inputs.registry-uri }}

    - run: npm run lint
      shell: bash
