name: Configure internal registry
description: Configure internal registry

inputs:
  uri:
    description: Registry URI
    required: true

  password:
    description: Registry password
    required: true

runs:
  using: composite
  steps:
    - run: touch ~/.npmrc
      shell: bash

    - run: echo "@stardust:registry=https:${{ inputs.uri }}/" >> ~/.npmrc
      shell: bash

    - run: echo "${{ inputs.uri }}/:_password=${{ inputs.password }}" >> ~/.npmrc
      shell: bash

    - run: echo "${{ inputs.uri }}/:username=_json_key_base64" >> ~/.npmrc
      shell: bash

    - run: echo "${{ inputs.uri }}/:email=not.valid@email.com" >> ~/.npmrc
      shell: bash
