name: Configure internal registry
description: Configure internal registry

inputs:
  registry-password:
    description: Internal registry password
    required: true

  registry-uri:
    description: Internal registry uri
    required: true

runs:
  using: composite
  steps:
    - name: Creating root ~/.npmrc file with internal registry config
      run: |
        touch ~/.npmrc
        echo "@stardust:registry=https:${{ inputs.registry-uri }}/" >> ~/.npmrc
        echo "${{ inputs.registry-uri }}/:_password=${{ inputs.registry-password }}" >> ~/.npmrc
        echo "${{ inputs.registry-uri }}/:username=_json_key_base64" >> ~/.npmrc
        echo "${{ inputs.registry-uri }}/:email=not.valid@email.com" >> ~/.npmrc
      shell: bash
