name: Publish Package to Internal Registry

description: Publish a package to the internal registry.

inputs:
  registry-password:
    description: The registry password
    required: true

  registry-uri:
    description: The registry URI
    required: true

  version:
    description: The type of version (path, minor, etc.)
    required: false
    default: patch

runs:
  using: composite
  steps:
    # - uses: actions/checkout@v2
    #   with:
    #     repository: stardusttech-io/actions
    #     ref: master
    #     token: ${{ inputs.github-token }}
    #     path: ./.github/actions

    - uses: ./.github/actions/authenticate-registry
      with:
        uri: ${{ inputs.registry-uri }}
        password: ${{ inputs.registry-password }}

    - name: Configuring git user email
      run: git config --global user.email "github-actions@stardusttech.io"
      shell: bash

    - name: Configuring git user name
      run: git config --global user.name "GitHub Actions"
      shell: bash

    - name: Versioning
      run: npm version ${{ inputs.version }}
      shell: bash

    - name: Publishing to internal registry
      run: npm publish
      shell: bash
