name: Install workflow

on:
  workflow_call:
    inputs:
      install-cache-name:
        type: string
        required: true

    secrets:
      registry-password:
        required: true

      registry-uri:
        required: true

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: stardusttech-io/gha/.github/actions/checkout-and-install@master
        with:
          install-cache-name: ${{ inputs.install-cache-name }}
          registry-password: ${{ secrets.registry-password }}
          registry-uri: ${{ secrets.registry-uri }}
