name: Internal package workflow

on:
  workflow_call:
    inputs:
      id:
        type: string
        required: true

      enable-build:
        type: boolean
        required: true

      enable-lint:
        type: boolean
        required: true

      enable-publish:
        type: boolean
        required: true

      enable-test:
        type: boolean
        required: true

      persist:
        type: string
        required: false

    secrets:
      registry-password:
        required: true

      registry-uri:
        required: true

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: stardusttech-io/gha/.github/actions/checkout-and-install@master
        with:
          id: ${{ inputs.id }}
          registry-password: ${{ secrets.registry-password }}
          registry-uri: ${{ secrets.registry-uri }}

  build:
    needs: [install]
    if: ${{ inputs.enable-build }}
    runs-on: ubuntu-latest
    steps:
      - uses: stardusttech-io/gha/.github/actions/build@master
        with:
          id: ${{ inputs.id }}
          persist: ${{ inputs.persist }}
          registry-password: ${{ secrets.registry-password }}
          registry-uri: ${{ secrets.registry-uri }}

  lint:
    needs: [install]
    if: ${{ inputs.enable-lint }}
    runs-on: ubuntu-latest
    steps:
      - uses: stardusttech-io/gha/.github/actions/lint@master
        with:
          id: ${{ inputs.id }}
          registry-password: ${{ inputs.registry-password }}
          registry-uri: ${{ inputs.registry-uri }}

  test:
    needs: [install]
    if: ${{ inputs.enable-test }}
    runs-on: ubuntu-latest
    steps:
      - uses: stardusttech-io/gha/.github/actions/test@master
        with:
          id: ${{ inputs.id }}
          registry-password: ${{ inputs.registry-password }}
          registry-uri: ${{ inputs.registry-uri }}

  publish:
    needs: [build, lint, test]
    runs-on: ubuntu-latest
    steps:
      - uses: stardusttech-io/gha/.github/actions/publish@master
        with:
          id: ${{ inputs.id }}
          persist: ${{ inputs.persist }}
          registry-password: ${{ secrets.registry-password }}
          registry-uri: ${{ secrets.registry-uri }}
