name: Package workflow

on:
  workflow_call:
    inputs:
      install-cache-name:
        type: string
        required: true

      build-artifact-name:
        type: string
        required: true

      enable-build:
        type: boolean
        required: true

      enable-lint:
        type: boolean
        required: true

      enable-publish:
        type: boolean
        required: true

      enable-test:
        type: boolean
        required: true

      persist:
        type: string
        required: false

    secrets:
      registry-access-token:
        required: true

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: stardusttech-io/gha/.github/actions/checkout-and-install@master
        with:
          install-cache-name: ${{ inputs.install-cache-name }}
          registry-access-token: ${{ secrets.registry-access-token }}

  build:
    needs: [install]
    if: ${{ inputs.enable-build }}
    runs-on: ubuntu-latest
    steps:
      - uses: stardusttech-io/gha/.github/actions/build@master
        with:
          build-artifact-name: ${{ inputs.build-artifact-name }}
          install-cache-name: ${{ inputs.install-cache-name }}
          persist: ${{ inputs.persist }}
          registry-access-token: ${{ secrets.registry-access-token }}

  lint:
    needs: [install]
    if: ${{ inputs.enable-lint }}
    runs-on: ubuntu-latest
    steps:
      - uses: stardusttech-io/gha/.github/actions/lint@master
        with:
          install-cache-name: ${{ inputs.install-cache-name }}
          registry-access-token: ${{ inputs.registry-access-token }}

  test:
    needs: [install]
    if: ${{ inputs.enable-test }}
    runs-on: ubuntu-latest
    steps:
      - uses: stardusttech-io/gha/.github/actions/test@master
        with:
          install-cache-name: ${{ inputs.install-cache-name }}
          registry-access-token: ${{ inputs.registry-access-token }}

  publish:
    needs: [build, lint, test]
    runs-on: ubuntu-latest
    steps:
      - uses: stardusttech-io/gha/.github/actions/publish@master
        with:
          build-artifact-name: ${{ inputs.build-artifact-name }}
          install-cache-name: ${{ inputs.install-cache-name }}
          persist: ${{ inputs.persist }}
          registry-access-token: ${{ secrets.registry-access-token }}
