name: Internal package workflow

on:
  workflow_call:
    inputs:
      publish:
        type: boolean
        required: false
        default: false

    secrets:
      registry-password:
        required: true

      registry-uri:
        required: true

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: stardusttech-io/gha/.github/actions/checkout-and-install@master
        with:
          registry-password: ${{ secrets.registry-password }}
          registry-uri: ${{ secrets.registry-uri }}

  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: stardusttech-io/gha/.github/actions/build@master
        with:
          build-artifact: package-build
          registry-password: ${{ secrets.registry-password }}
          registry-uri: ${{ secrets.registry-uri }}

  publish:
    needs: build
    if: ${{ inputs.publish }}
    runs-on: ubuntu-latest
    steps:
      - uses: stardusttech-io/gha/.github/actions/publish@master
        with:
          build-artifact: package-build
          registry-password: ${{ secrets.registry-password }}
          registry-uri: ${{ secrets.registry-uri }}
