name: Package workflow

on:
  workflow_call:
    inputs:
      install-cache-name:
        type: string
        required: true

      build-artifact-name:
        type: string
        required: true

      enable-build:
        type: boolean
        required: true

      enable-lint:
        type: boolean
        required: true

      enable-test:
        type: boolean
        required: true

      persist:
        type: string
        required: false

      workspace:
        type: string
        required: true

    secrets:
      registry-access-token:
        required: true

jobs:
  build:
    name: Build
    if: ${{ inputs.enable-build }}
    runs-on: ubuntu-latest
    steps:
      - uses: stardusttech-io/gha/.github/actions/build@master
        with:
          build-artifact-name: ${{ inputs.build-artifact-name }}
          install-cache-name: ${{ inputs.install-cache-name }}
          persist: ${{ inputs.persist }}
          registry-access-token: ${{ secrets.registry-access-token }}
          workspace: ${{ inputs.workspace }}

  lint:
    name: Lint
    if: ${{ inputs.enable-lint }}
    runs-on: ubuntu-latest
    steps:
      - uses: stardusttech-io/gha/.github/actions/lint@master
        with:
          install-cache-name: ${{ inputs.install-cache-name }}
          registry-access-token: ${{ inputs.registry-access-token }}
          workspace: ${{ inputs.workspace }}

  test:
    name: Test
    if: ${{ inputs.enable-test }}
    runs-on: ubuntu-latest
    steps:
      - uses: stardusttech-io/gha/.github/actions/test@master
        with:
          install-cache-name: ${{ inputs.install-cache-name }}
          registry-access-token: ${{ inputs.registry-access-token }}
          workspace: ${{ inputs.workspace }}
